name: Documentation Maintenance

on:
  push:
    paths:
      - 'src/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - '*.md'
  schedule:
    # Weekly Monday 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  staleness-check:
    name: Check Doc Staleness
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for git log dates

      - name: Make script executable
        run: chmod +x ./scripts/docs-staleness-check.sh

      - name: Run staleness check
        id: check
        run: |
          set +e
          ./scripts/docs-staleness-check.sh 2>&1 | tee staleness-output.txt
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Comment on PR (if stale)
        if: github.event_name == 'pull_request' && steps.check.outputs.exit_code != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('staleness-output.txt', 'utf8');
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## 📚 Documentation Staleness Check Failed\n\n\`\`\`\n${output}\n\`\`\`\n\nPlease update stale docs before merging.`
            });

      - name: Create issue (scheduled run)
        if: github.event_name == 'schedule' && steps.check.outputs.exit_code != '0'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('staleness-output.txt', 'utf8');
            const title = `📚 Weekly Docs Maintenance Required - ${new Date().toISOString().split('T')[0]}`;
            
            // Check for existing open issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'documentation,maintenance'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: `## Stale Documentation Detected\n\n\`\`\`\n${output}\n\`\`\`\n\nPlease review and update these docs.`,
                labels: ['documentation', 'maintenance']
              });
            }

      - name: Fail if stale
        if: steps.check.outputs.exit_code != '0'
        run: exit 1

  lint-check:
    name: Lint Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check frontmatter
        run: |
          errors=0
          for doc in docs/**/*.md; do
            [[ ! -f "$doc" ]] && continue
            [[ "$doc" == *"index.md" ]] && continue
            [[ "$doc" == *"MAINTENANCE.md" ]] && continue
            
            if ! head -1 "$doc" | grep -q "^---"; then
              echo "❌ $doc: missing frontmatter"
              errors=$((errors + 1))
            fi
          done
          exit $errors

      - name: Check See Also sections
        run: |
          warnings=0
          for doc in docs/**/*.md; do
            [[ ! -f "$doc" ]] && continue
            [[ "$doc" == *"index.md" ]] && continue
            [[ "$doc" == *"MAINTENANCE.md" ]] && continue
            [[ "$doc" == *"paths/"* ]] && continue
            
            if ! grep -q "^## See Also" "$doc"; then
              echo "⚠️  $doc: missing See Also section"
              warnings=$((warnings + 1))
            fi
          done
          echo "Warnings: $warnings"
          # Don't fail on warnings, just report
